FROM golang:latest AS build 

WORKDIR /go/judge

COPY go.mod go.sum /go/judge/

RUN go mod download

COPY ./ /go/judge

RUN go build -o executorserver ./cmd/executorserver  

FROM debian:latest

WORKDIR /opt

COPY --from=build /go/judge/executorserver /opt/

EXPOSE 5050/tcp

ENTRYPOINT ["./executorserver"]
