FROM golang:latest AS build 

WORKDIR /go/judge

COPY go.mod go.sum /go/judge/

RUN go mod download

COPY ./ /go/judge

RUN go build -o executorserver ./cmd/executorserver \
    go build -o cinit ./cmd/cinit && \
    go build -buildmode=c-shared -o executor_server.so ./cmd/ffi/

FROM debian:latest

WORKDIR /opt

COPY --from=build /go/judge/executorserver /go/judge/mount.yaml /opt/

EXPOSE 5050/tcp 5051/tcp

ENTRYPOINT ["./executorserver"]
