// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: file.proto

//go:build protoopaque

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileID struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FileID string                 `protobuf:"bytes,1,opt,name=fileID"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FileID) Reset() {
	*x = FileID{}
	mi := &file_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileID) ProtoMessage() {}

func (x *FileID) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FileID) GetFileID() string {
	if x != nil {
		return x.xxx_hidden_FileID
	}
	return ""
}

func (x *FileID) SetFileID(v string) {
	x.xxx_hidden_FileID = v
}

type FileID_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	FileID string
}

func (b0 FileID_builder) Build() *FileID {
	m0 := &FileID{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_FileID = b.FileID
	return m0
}

type FileContent struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name    string                 `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Content []byte                 `protobuf:"bytes,2,opt,name=content"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FileContent) Reset() {
	*x = FileContent{}
	mi := &file_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileContent) ProtoMessage() {}

func (x *FileContent) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FileContent) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *FileContent) GetContent() []byte {
	if x != nil {
		return x.xxx_hidden_Content
	}
	return nil
}

func (x *FileContent) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *FileContent) SetContent(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Content = v
}

type FileContent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name    string
	Content []byte
}

func (b0 FileContent_builder) Build() *FileContent {
	m0 := &FileContent{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Content = b.Content
	return m0
}

type FileListType struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FileIDs map[string]string      `protobuf:"bytes,1,rep,name=fileIDs" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FileListType) Reset() {
	*x = FileListType{}
	mi := &file_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileListType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListType) ProtoMessage() {}

func (x *FileListType) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FileListType) GetFileIDs() map[string]string {
	if x != nil {
		return x.xxx_hidden_FileIDs
	}
	return nil
}

func (x *FileListType) SetFileIDs(v map[string]string) {
	x.xxx_hidden_FileIDs = v
}

type FileListType_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	FileIDs map[string]string
}

func (b0 FileListType_builder) Build() *FileListType {
	m0 := &FileListType{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_FileIDs = b.FileIDs
	return m0
}

var File_file_proto protoreflect.FileDescriptor

const file_file_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"file.proto\x12\x02pb\x1a!google/protobuf/go_features.proto\" \n" +
	"\x06FileID\x12\x16\n" +
	"\x06fileID\x18\x01 \x01(\tR\x06fileID\";\n" +
	"\vFileContent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"\x83\x01\n" +
	"\fFileListType\x127\n" +
	"\afileIDs\x18\x01 \x03(\v2\x1d.pb.FileListType.FileIDsEntryR\afileIDs\x1a:\n" +
	"\fFileIDsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B)Z\x1dgithub.com/criyle/go-judge/pb\x92\x03\a\xd2>\x02\x10\x02\b\x02b\beditionsp\xe8\a"

var file_file_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_file_proto_goTypes = []any{
	(*FileID)(nil),       // 0: pb.FileID
	(*FileContent)(nil),  // 1: pb.FileContent
	(*FileListType)(nil), // 2: pb.FileListType
	nil,                  // 3: pb.FileListType.FileIDsEntry
}
var file_file_proto_depIdxs = []int32{
	3, // 0: pb.FileListType.fileIDs:type_name -> pb.FileListType.FileIDsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_file_proto_init() }
func file_file_proto_init() {
	if File_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_proto_rawDesc), len(file_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_file_proto_goTypes,
		DependencyIndexes: file_file_proto_depIdxs,
		MessageInfos:      file_file_proto_msgTypes,
	}.Build()
	File_file_proto = out.File
	file_file_proto_goTypes = nil
	file_file_proto_depIdxs = nil
}
