// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: response.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response_FileError_ErrorType int32

const (
	Response_FileError_CopyInOpenFile        Response_FileError_ErrorType = 0
	Response_FileError_CopyInCreateFile      Response_FileError_ErrorType = 1
	Response_FileError_CopyInCopyContent     Response_FileError_ErrorType = 2
	Response_FileError_CopyOutOpen           Response_FileError_ErrorType = 3
	Response_FileError_CopyOutNotRegularFile Response_FileError_ErrorType = 4
	Response_FileError_CopyOutSizeExceeded   Response_FileError_ErrorType = 5
	Response_FileError_CopyOutCreateFile     Response_FileError_ErrorType = 6
	Response_FileError_CopyOutCopyContent    Response_FileError_ErrorType = 7
	Response_FileError_CollectSizeExceeded   Response_FileError_ErrorType = 8
	Response_FileError_Symlink               Response_FileError_ErrorType = 9
)

// Enum value maps for Response_FileError_ErrorType.
var (
	Response_FileError_ErrorType_name = map[int32]string{
		0: "CopyInOpenFile",
		1: "CopyInCreateFile",
		2: "CopyInCopyContent",
		3: "CopyOutOpen",
		4: "CopyOutNotRegularFile",
		5: "CopyOutSizeExceeded",
		6: "CopyOutCreateFile",
		7: "CopyOutCopyContent",
		8: "CollectSizeExceeded",
		9: "Symlink",
	}
	Response_FileError_ErrorType_value = map[string]int32{
		"CopyInOpenFile":        0,
		"CopyInCreateFile":      1,
		"CopyInCopyContent":     2,
		"CopyOutOpen":           3,
		"CopyOutNotRegularFile": 4,
		"CopyOutSizeExceeded":   5,
		"CopyOutCreateFile":     6,
		"CopyOutCopyContent":    7,
		"CollectSizeExceeded":   8,
		"Symlink":               9,
	}
)

func (x Response_FileError_ErrorType) Enum() *Response_FileError_ErrorType {
	p := new(Response_FileError_ErrorType)
	*p = x
	return p
}

func (x Response_FileError_ErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Response_FileError_ErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_response_proto_enumTypes[0].Descriptor()
}

func (Response_FileError_ErrorType) Type() protoreflect.EnumType {
	return &file_response_proto_enumTypes[0]
}

func (x Response_FileError_ErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Response_FileError_ErrorType.Descriptor instead.
func (Response_FileError_ErrorType) EnumDescriptor() ([]byte, []int) {
	return file_response_proto_rawDescGZIP(), []int{0, 0, 0}
}

type Response_Result_StatusType int32

const (
	Response_Result_Invalid             Response_Result_StatusType = 0
	Response_Result_Accepted            Response_Result_StatusType = 1
	Response_Result_WrongAnswer         Response_Result_StatusType = 2 // Not used
	Response_Result_PartiallyCorrect    Response_Result_StatusType = 3 // Not used
	Response_Result_MemoryLimitExceeded Response_Result_StatusType = 4
	Response_Result_TimeLimitExceeded   Response_Result_StatusType = 5
	Response_Result_OutputLimitExceeded Response_Result_StatusType = 6
	Response_Result_FileError           Response_Result_StatusType = 7
	Response_Result_NonZeroExitStatus   Response_Result_StatusType = 8
	Response_Result_Signalled           Response_Result_StatusType = 9
	Response_Result_DangerousSyscall    Response_Result_StatusType = 10
	Response_Result_JudgementFailed     Response_Result_StatusType = 11 // Not used
	Response_Result_InvalidInteraction  Response_Result_StatusType = 12 // Not used
	Response_Result_InternalError       Response_Result_StatusType = 13
)

// Enum value maps for Response_Result_StatusType.
var (
	Response_Result_StatusType_name = map[int32]string{
		0:  "Invalid",
		1:  "Accepted",
		2:  "WrongAnswer",
		3:  "PartiallyCorrect",
		4:  "MemoryLimitExceeded",
		5:  "TimeLimitExceeded",
		6:  "OutputLimitExceeded",
		7:  "FileError",
		8:  "NonZeroExitStatus",
		9:  "Signalled",
		10: "DangerousSyscall",
		11: "JudgementFailed",
		12: "InvalidInteraction",
		13: "InternalError",
	}
	Response_Result_StatusType_value = map[string]int32{
		"Invalid":             0,
		"Accepted":            1,
		"WrongAnswer":         2,
		"PartiallyCorrect":    3,
		"MemoryLimitExceeded": 4,
		"TimeLimitExceeded":   5,
		"OutputLimitExceeded": 6,
		"FileError":           7,
		"NonZeroExitStatus":   8,
		"Signalled":           9,
		"DangerousSyscall":    10,
		"JudgementFailed":     11,
		"InvalidInteraction":  12,
		"InternalError":       13,
	}
)

func (x Response_Result_StatusType) Enum() *Response_Result_StatusType {
	p := new(Response_Result_StatusType)
	*p = x
	return p
}

func (x Response_Result_StatusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Response_Result_StatusType) Descriptor() protoreflect.EnumDescriptor {
	return file_response_proto_enumTypes[1].Descriptor()
}

func (Response_Result_StatusType) Type() protoreflect.EnumType {
	return &file_response_proto_enumTypes[1]
}

func (x Response_Result_StatusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Response_Result_StatusType.Descriptor instead.
func (Response_Result_StatusType) EnumDescriptor() ([]byte, []int) {
	return file_response_proto_rawDescGZIP(), []int{0, 1, 0}
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestID     string                 `protobuf:"bytes,1,opt,name=requestID" json:"requestID,omitempty"`
	Results       []*Response_Result     `protobuf:"bytes,2,rep,name=results" json:"results,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_response_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *Response) GetResults() []*Response_Result {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Response_FileError struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Name          string                       `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type          Response_FileError_ErrorType `protobuf:"varint,2,opt,name=type,enum=pb.Response_FileError_ErrorType" json:"type,omitempty"`
	Message       string                       `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response_FileError) Reset() {
	*x = Response_FileError{}
	mi := &file_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response_FileError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_FileError) ProtoMessage() {}

func (x *Response_FileError) ProtoReflect() protoreflect.Message {
	mi := &file_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_FileError.ProtoReflect.Descriptor instead.
func (*Response_FileError) Descriptor() ([]byte, []int) {
	return file_response_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Response_FileError) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Response_FileError) GetType() Response_FileError_ErrorType {
	if x != nil {
		return x.Type
	}
	return Response_FileError_CopyInOpenFile
}

func (x *Response_FileError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Response_Result struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Status        Response_Result_StatusType `protobuf:"varint,1,opt,name=status,enum=pb.Response_Result_StatusType" json:"status,omitempty"`
	ExitStatus    int32                      `protobuf:"varint,2,opt,name=exitStatus" json:"exitStatus,omitempty"`
	Error         string                     `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	Time          uint64                     `protobuf:"varint,4,opt,name=time" json:"time,omitempty"`
	RunTime       uint64                     `protobuf:"varint,8,opt,name=runTime" json:"runTime,omitempty"`
	ProcPeak      uint64                     `protobuf:"varint,10,opt,name=procPeak" json:"procPeak,omitempty"`
	Memory        uint64                     `protobuf:"varint,5,opt,name=memory" json:"memory,omitempty"`
	Files         map[string][]byte          `protobuf:"bytes,6,rep,name=files" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FileIDs       map[string]string          `protobuf:"bytes,7,rep,name=fileIDs" json:"fileIDs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FileError     []*Response_FileError      `protobuf:"bytes,9,rep,name=fileError" json:"fileError,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response_Result) Reset() {
	*x = Response_Result{}
	mi := &file_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_Result) ProtoMessage() {}

func (x *Response_Result) ProtoReflect() protoreflect.Message {
	mi := &file_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_Result.ProtoReflect.Descriptor instead.
func (*Response_Result) Descriptor() ([]byte, []int) {
	return file_response_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Response_Result) GetStatus() Response_Result_StatusType {
	if x != nil {
		return x.Status
	}
	return Response_Result_Invalid
}

func (x *Response_Result) GetExitStatus() int32 {
	if x != nil {
		return x.ExitStatus
	}
	return 0
}

func (x *Response_Result) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Response_Result) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Response_Result) GetRunTime() uint64 {
	if x != nil {
		return x.RunTime
	}
	return 0
}

func (x *Response_Result) GetProcPeak() uint64 {
	if x != nil {
		return x.ProcPeak
	}
	return 0
}

func (x *Response_Result) GetMemory() uint64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *Response_Result) GetFiles() map[string][]byte {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *Response_Result) GetFileIDs() map[string]string {
	if x != nil {
		return x.FileIDs
	}
	return nil
}

func (x *Response_Result) GetFileError() []*Response_FileError {
	if x != nil {
		return x.FileError
	}
	return nil
}

var File_response_proto protoreflect.FileDescriptor

const file_response_proto_rawDesc = "" +
	"\n" +
	"\x0eresponse.proto\x12\x02pb\"\xe6\t\n" +
	"\bResponse\x12\x1c\n" +
	"\trequestID\x18\x01 \x01(\tR\trequestID\x12-\n" +
	"\aresults\x18\x02 \x03(\v2\x13.pb.Response.ResultR\aresults\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x1a\xd8\x02\n" +
	"\tFileError\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\x04type\x18\x02 \x01(\x0e2 .pb.Response.FileError.ErrorTypeR\x04type\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xe6\x01\n" +
	"\tErrorType\x12\x12\n" +
	"\x0eCopyInOpenFile\x10\x00\x12\x14\n" +
	"\x10CopyInCreateFile\x10\x01\x12\x15\n" +
	"\x11CopyInCopyContent\x10\x02\x12\x0f\n" +
	"\vCopyOutOpen\x10\x03\x12\x19\n" +
	"\x15CopyOutNotRegularFile\x10\x04\x12\x17\n" +
	"\x13CopyOutSizeExceeded\x10\x05\x12\x15\n" +
	"\x11CopyOutCreateFile\x10\x06\x12\x16\n" +
	"\x12CopyOutCopyContent\x10\a\x12\x17\n" +
	"\x13CollectSizeExceeded\x10\b\x12\v\n" +
	"\aSymlink\x10\t\x1a\x9b\x06\n" +
	"\x06Result\x126\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1e.pb.Response.Result.StatusTypeR\x06status\x12\x1e\n" +
	"\n" +
	"exitStatus\x18\x02 \x01(\x05R\n" +
	"exitStatus\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x12\n" +
	"\x04time\x18\x04 \x01(\x04R\x04time\x12\x18\n" +
	"\arunTime\x18\b \x01(\x04R\arunTime\x12\x1a\n" +
	"\bprocPeak\x18\n" +
	" \x01(\x04R\bprocPeak\x12\x16\n" +
	"\x06memory\x18\x05 \x01(\x04R\x06memory\x124\n" +
	"\x05files\x18\x06 \x03(\v2\x1e.pb.Response.Result.FilesEntryR\x05files\x12:\n" +
	"\afileIDs\x18\a \x03(\v2 .pb.Response.Result.FileIDsEntryR\afileIDs\x124\n" +
	"\tfileError\x18\t \x03(\v2\x16.pb.Response.FileErrorR\tfileError\x1a8\n" +
	"\n" +
	"FilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a:\n" +
	"\fFileIDsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa2\x02\n" +
	"\n" +
	"StatusType\x12\v\n" +
	"\aInvalid\x10\x00\x12\f\n" +
	"\bAccepted\x10\x01\x12\x0f\n" +
	"\vWrongAnswer\x10\x02\x12\x14\n" +
	"\x10PartiallyCorrect\x10\x03\x12\x17\n" +
	"\x13MemoryLimitExceeded\x10\x04\x12\x15\n" +
	"\x11TimeLimitExceeded\x10\x05\x12\x17\n" +
	"\x13OutputLimitExceeded\x10\x06\x12\r\n" +
	"\tFileError\x10\a\x12\x15\n" +
	"\x11NonZeroExitStatus\x10\b\x12\r\n" +
	"\tSignalled\x10\t\x12\x14\n" +
	"\x10DangerousSyscall\x10\n" +
	"\x12\x13\n" +
	"\x0fJudgementFailed\x10\v\x12\x16\n" +
	"\x12InvalidInteraction\x10\f\x12\x11\n" +
	"\rInternalError\x10\rB$Z\x1dgithub.com/criyle/go-judge/pb\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var (
	file_response_proto_rawDescOnce sync.Once
	file_response_proto_rawDescData []byte
)

func file_response_proto_rawDescGZIP() []byte {
	file_response_proto_rawDescOnce.Do(func() {
		file_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_response_proto_rawDesc), len(file_response_proto_rawDesc)))
	})
	return file_response_proto_rawDescData
}

var file_response_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_response_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_response_proto_goTypes = []any{
	(Response_FileError_ErrorType)(0), // 0: pb.Response.FileError.ErrorType
	(Response_Result_StatusType)(0),   // 1: pb.Response.Result.StatusType
	(*Response)(nil),                  // 2: pb.Response
	(*Response_FileError)(nil),        // 3: pb.Response.FileError
	(*Response_Result)(nil),           // 4: pb.Response.Result
	nil,                               // 5: pb.Response.Result.FilesEntry
	nil,                               // 6: pb.Response.Result.FileIDsEntry
}
var file_response_proto_depIdxs = []int32{
	4, // 0: pb.Response.results:type_name -> pb.Response.Result
	0, // 1: pb.Response.FileError.type:type_name -> pb.Response.FileError.ErrorType
	1, // 2: pb.Response.Result.status:type_name -> pb.Response.Result.StatusType
	5, // 3: pb.Response.Result.files:type_name -> pb.Response.Result.FilesEntry
	6, // 4: pb.Response.Result.fileIDs:type_name -> pb.Response.Result.FileIDsEntry
	3, // 5: pb.Response.Result.fileError:type_name -> pb.Response.FileError
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_response_proto_init() }
func file_response_proto_init() {
	if File_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_response_proto_rawDesc), len(file_response_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_response_proto_goTypes,
		DependencyIndexes: file_response_proto_depIdxs,
		EnumInfos:         file_response_proto_enumTypes,
		MessageInfos:      file_response_proto_msgTypes,
	}.Build()
	File_response_proto = out.File
	file_response_proto_goTypes = nil
	file_response_proto_depIdxs = nil
}
