// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: stream_request.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*StreamRequest_ExecRequest
	//	*StreamRequest_ExecInput
	//	*StreamRequest_ExecResize
	//	*StreamRequest_ExecCancel
	Request       isStreamRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_stream_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_stream_request_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetRequest() isStreamRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *StreamRequest) GetExecRequest() *Request {
	if x != nil {
		if x, ok := x.Request.(*StreamRequest_ExecRequest); ok {
			return x.ExecRequest
		}
	}
	return nil
}

func (x *StreamRequest) GetExecInput() *StreamRequest_Input {
	if x != nil {
		if x, ok := x.Request.(*StreamRequest_ExecInput); ok {
			return x.ExecInput
		}
	}
	return nil
}

func (x *StreamRequest) GetExecResize() *StreamRequest_Resize {
	if x != nil {
		if x, ok := x.Request.(*StreamRequest_ExecResize); ok {
			return x.ExecResize
		}
	}
	return nil
}

func (x *StreamRequest) GetExecCancel() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Request.(*StreamRequest_ExecCancel); ok {
			return x.ExecCancel
		}
	}
	return nil
}

type isStreamRequest_Request interface {
	isStreamRequest_Request()
}

type StreamRequest_ExecRequest struct {
	ExecRequest *Request `protobuf:"bytes,1,opt,name=execRequest,oneof"`
}

type StreamRequest_ExecInput struct {
	ExecInput *StreamRequest_Input `protobuf:"bytes,2,opt,name=execInput,oneof"`
}

type StreamRequest_ExecResize struct {
	ExecResize *StreamRequest_Resize `protobuf:"bytes,3,opt,name=execResize,oneof"`
}

type StreamRequest_ExecCancel struct {
	ExecCancel *emptypb.Empty `protobuf:"bytes,4,opt,name=execCancel,oneof"`
}

func (*StreamRequest_ExecRequest) isStreamRequest_Request() {}

func (*StreamRequest_ExecInput) isStreamRequest_Request() {}

func (*StreamRequest_ExecResize) isStreamRequest_Request() {}

func (*StreamRequest_ExecCancel) isStreamRequest_Request() {}

type StreamRequest_Input struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Fd            uint32                 `protobuf:"varint,3,opt,name=fd" json:"fd,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest_Input) Reset() {
	*x = StreamRequest_Input{}
	mi := &file_stream_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest_Input) ProtoMessage() {}

func (x *StreamRequest_Input) ProtoReflect() protoreflect.Message {
	mi := &file_stream_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest_Input.ProtoReflect.Descriptor instead.
func (*StreamRequest_Input) Descriptor() ([]byte, []int) {
	return file_stream_request_proto_rawDescGZIP(), []int{0, 0}
}

func (x *StreamRequest_Input) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *StreamRequest_Input) GetFd() uint32 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *StreamRequest_Input) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type StreamRequest_Resize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Fd            uint32                 `protobuf:"varint,6,opt,name=fd" json:"fd,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows" json:"rows,omitempty"`
	Cols          uint32                 `protobuf:"varint,3,opt,name=cols" json:"cols,omitempty"`
	X             uint32                 `protobuf:"varint,4,opt,name=x" json:"x,omitempty"`
	Y             uint32                 `protobuf:"varint,5,opt,name=y" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest_Resize) Reset() {
	*x = StreamRequest_Resize{}
	mi := &file_stream_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest_Resize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest_Resize) ProtoMessage() {}

func (x *StreamRequest_Resize) ProtoReflect() protoreflect.Message {
	mi := &file_stream_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest_Resize.ProtoReflect.Descriptor instead.
func (*StreamRequest_Resize) Descriptor() ([]byte, []int) {
	return file_stream_request_proto_rawDescGZIP(), []int{0, 1}
}

func (x *StreamRequest_Resize) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *StreamRequest_Resize) GetFd() uint32 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *StreamRequest_Resize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *StreamRequest_Resize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *StreamRequest_Resize) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *StreamRequest_Resize) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_stream_request_proto protoreflect.FileDescriptor

const file_stream_request_proto_rawDesc = "" +
	"\n" +
	"\x14stream_request.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\x1a\rrequest.proto\"\xb7\x03\n" +
	"\rStreamRequest\x12/\n" +
	"\vexecRequest\x18\x01 \x01(\v2\v.pb.RequestH\x00R\vexecRequest\x127\n" +
	"\texecInput\x18\x02 \x01(\v2\x17.pb.StreamRequest.InputH\x00R\texecInput\x12:\n" +
	"\n" +
	"execResize\x18\x03 \x01(\v2\x18.pb.StreamRequest.ResizeH\x00R\n" +
	"execResize\x128\n" +
	"\n" +
	"execCancel\x18\x04 \x01(\v2\x16.google.protobuf.EmptyH\x00R\n" +
	"execCancel\x1aG\n" +
	"\x05Input\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x0e\n" +
	"\x02fd\x18\x03 \x01(\rR\x02fd\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x1ar\n" +
	"\x06Resize\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x0e\n" +
	"\x02fd\x18\x06 \x01(\rR\x02fd\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x03 \x01(\rR\x04cols\x12\f\n" +
	"\x01x\x18\x04 \x01(\rR\x01x\x12\f\n" +
	"\x01y\x18\x05 \x01(\rR\x01yB\t\n" +
	"\arequestB$Z\x1dgithub.com/criyle/go-judge/pb\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var (
	file_stream_request_proto_rawDescOnce sync.Once
	file_stream_request_proto_rawDescData []byte
)

func file_stream_request_proto_rawDescGZIP() []byte {
	file_stream_request_proto_rawDescOnce.Do(func() {
		file_stream_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stream_request_proto_rawDesc), len(file_stream_request_proto_rawDesc)))
	})
	return file_stream_request_proto_rawDescData
}

var file_stream_request_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_stream_request_proto_goTypes = []any{
	(*StreamRequest)(nil),        // 0: pb.StreamRequest
	(*StreamRequest_Input)(nil),  // 1: pb.StreamRequest.Input
	(*StreamRequest_Resize)(nil), // 2: pb.StreamRequest.Resize
	(*Request)(nil),              // 3: pb.Request
	(*emptypb.Empty)(nil),        // 4: google.protobuf.Empty
}
var file_stream_request_proto_depIdxs = []int32{
	3, // 0: pb.StreamRequest.execRequest:type_name -> pb.Request
	1, // 1: pb.StreamRequest.execInput:type_name -> pb.StreamRequest.Input
	2, // 2: pb.StreamRequest.execResize:type_name -> pb.StreamRequest.Resize
	4, // 3: pb.StreamRequest.execCancel:type_name -> google.protobuf.Empty
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_stream_request_proto_init() }
func file_stream_request_proto_init() {
	if File_stream_request_proto != nil {
		return
	}
	file_request_proto_init()
	file_stream_request_proto_msgTypes[0].OneofWrappers = []any{
		(*StreamRequest_ExecRequest)(nil),
		(*StreamRequest_ExecInput)(nil),
		(*StreamRequest_ExecResize)(nil),
		(*StreamRequest_ExecCancel)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stream_request_proto_rawDesc), len(file_stream_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stream_request_proto_goTypes,
		DependencyIndexes: file_stream_request_proto_depIdxs,
		MessageInfos:      file_stream_request_proto_msgTypes,
	}.Build()
	File_stream_request_proto = out.File
	file_stream_request_proto_goTypes = nil
	file_stream_request_proto_depIdxs = nil
}
