// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: stream_response.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*StreamResponse_ExecResponse
	//	*StreamResponse_ExecOutput
	Response      isStreamResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_stream_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_stream_response_proto_rawDescGZIP(), []int{0}
}

func (x *StreamResponse) GetResponse() isStreamResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *StreamResponse) GetExecResponse() *Response {
	if x != nil {
		if x, ok := x.Response.(*StreamResponse_ExecResponse); ok {
			return x.ExecResponse
		}
	}
	return nil
}

func (x *StreamResponse) GetExecOutput() *StreamResponse_Output {
	if x != nil {
		if x, ok := x.Response.(*StreamResponse_ExecOutput); ok {
			return x.ExecOutput
		}
	}
	return nil
}

type isStreamResponse_Response interface {
	isStreamResponse_Response()
}

type StreamResponse_ExecResponse struct {
	ExecResponse *Response `protobuf:"bytes,1,opt,name=execResponse,oneof"`
}

type StreamResponse_ExecOutput struct {
	ExecOutput *StreamResponse_Output `protobuf:"bytes,2,opt,name=execOutput,oneof"`
}

func (*StreamResponse_ExecResponse) isStreamResponse_Response() {}

func (*StreamResponse_ExecOutput) isStreamResponse_Response() {}

type StreamResponse_Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Fd            uint32                 `protobuf:"varint,3,opt,name=fd" json:"fd,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse_Output) Reset() {
	*x = StreamResponse_Output{}
	mi := &file_stream_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse_Output) ProtoMessage() {}

func (x *StreamResponse_Output) ProtoReflect() protoreflect.Message {
	mi := &file_stream_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse_Output.ProtoReflect.Descriptor instead.
func (*StreamResponse_Output) Descriptor() ([]byte, []int) {
	return file_stream_response_proto_rawDescGZIP(), []int{0, 0}
}

func (x *StreamResponse_Output) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *StreamResponse_Output) GetFd() uint32 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *StreamResponse_Output) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_stream_response_proto protoreflect.FileDescriptor

const file_stream_response_proto_rawDesc = "" +
	"\n" +
	"\x15stream_response.proto\x12\x02pb\x1a\x0eresponse.proto\"\xd7\x01\n" +
	"\x0eStreamResponse\x122\n" +
	"\fexecResponse\x18\x01 \x01(\v2\f.pb.ResponseH\x00R\fexecResponse\x12;\n" +
	"\n" +
	"execOutput\x18\x02 \x01(\v2\x19.pb.StreamResponse.OutputH\x00R\n" +
	"execOutput\x1aH\n" +
	"\x06Output\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x0e\n" +
	"\x02fd\x18\x03 \x01(\rR\x02fd\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontentB\n" +
	"\n" +
	"\bresponseB$Z\x1dgithub.com/criyle/go-judge/pb\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var (
	file_stream_response_proto_rawDescOnce sync.Once
	file_stream_response_proto_rawDescData []byte
)

func file_stream_response_proto_rawDescGZIP() []byte {
	file_stream_response_proto_rawDescOnce.Do(func() {
		file_stream_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stream_response_proto_rawDesc), len(file_stream_response_proto_rawDesc)))
	})
	return file_stream_response_proto_rawDescData
}

var file_stream_response_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_stream_response_proto_goTypes = []any{
	(*StreamResponse)(nil),        // 0: pb.StreamResponse
	(*StreamResponse_Output)(nil), // 1: pb.StreamResponse.Output
	(*Response)(nil),              // 2: pb.Response
}
var file_stream_response_proto_depIdxs = []int32{
	2, // 0: pb.StreamResponse.execResponse:type_name -> pb.Response
	1, // 1: pb.StreamResponse.execOutput:type_name -> pb.StreamResponse.Output
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_stream_response_proto_init() }
func file_stream_response_proto_init() {
	if File_stream_response_proto != nil {
		return
	}
	file_response_proto_init()
	file_stream_response_proto_msgTypes[0].OneofWrappers = []any{
		(*StreamResponse_ExecResponse)(nil),
		(*StreamResponse_ExecOutput)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stream_response_proto_rawDesc), len(file_stream_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stream_response_proto_goTypes,
		DependencyIndexes: file_stream_response_proto_depIdxs,
		MessageInfos:      file_stream_response_proto_msgTypes,
	}.Build()
	File_stream_response_proto = out.File
	file_stream_response_proto_goTypes = nil
	file_stream_response_proto_depIdxs = nil
}
